### ISSUE TITLE
Fix deployment issues

### ISSUE THREAD

**Issue by tomaskulich** [vacuumlabs/report-bot#28]
Page takes a long time to load, when accessed after long time of inactivity. Probably `now` suspends the server if no requests come in and then it takes too long to resume it?

I'd also consider migrating away from `now` to heroku, if now is giving us a hard time.

**Comment by mlenik** [comment]
The app is migrated to Heroku so this issue shouldn't be valid anymore. If it's still the case, pls reopen it.
