### ISSUE TITLE
Performance tuning

### ISSUE THREAD

**Issue by tomaskulich** [vacuumlabs/report-bot#34]
Load all the reports with the very first request to the page. All other interactions with the page should happen without firing any additional requests to the server.

The reports should be refreshed every 5 minutes. This should happen in the background without blocking users in their work and without showing any 'reloading' state.

Finally, it seems to me that the requests take too long to respond. For example 'capacity' reports contain 30kB, yet it takes almost 3s to fetch them.. why is this so? It should be an order of magnitude faster.

**Comment by leanil** [comment]
Just to clarify: should I load all the reports before responding anything to the first request?
I would at least render the sidebar and the general frame of the page while loading the reports.

**Comment by tomaskulich** [comment]
I don't care about the details of the rendering that much, but the page without reports is quite useless probably.

All the reports together will be far less than 1M in size. The server can have those precomputed, so it's just about transferring the data - that should be really quick.
